from sqlalchemy.types import Date, Float, Integer, String, Text, TypeEngine


def sqlalchemy_to_pandas_dtypes(sql_dtypes: dict[str, TypeEngine]) -> tuple[dict[str, str], list[str]]:
    dtypes = {}
    date_cols = []

    for col, typ in sql_dtypes.items():
        if isinstance(typ, Integer):
            dtypes[col] = "Int64"  # nullable integer

        elif isinstance(typ, Float):
            dtypes[col] = "float64"

        elif isinstance(typ, (String, Text)):
            dtypes[col] = "string"

        elif isinstance(typ, Date):
            date_cols.append(col)

        else:
            raise TypeError(f"Unsupported SQLAlchemy type: {typ}")

    return dtypes, date_cols


dtypes: dict[str, TypeEngine] = {
    "pitch_type": String(length=2),
    "game_date": Date(),
    "release_speed": Float(),
    "release_pos_x": Float(),
    "release_pos_z": Float(),
    "player_name": Text(),
    "batter": Integer(),
    "pitcher": Integer(),
    "events": Text(),
    "description": Text(),
    "spin_dir": Float(),
    "spin_rate_deprecated": Float(),
    "break_angle_deprecated": Float(),
    "break_length_deprecated": Float(),
    "zone": Float(),
    "des": Text(),
    "game_type": String(length=1),
    "stand": String(length=1),
    "p_throws": String(length=1),
    "home_team": String(length=3),
    "away_team": String(length=3),
    "type": String(length=1),
    "hit_location": Float(),
    "bb_type": Text(),
    "balls": Integer(),
    "strikes": Integer(),
    "game_year": Integer(),
    "pfx_x": Float(),
    "pfx_z": Float(),
    "plate_x": Float(),
    "plate_z": Float(),
    "on_3b": Float(),
    "on_2b": Float(),
    "on_1b": Float(),
    "outs_when_up": Integer(),
    "inning": Integer(),
    "inning_topbot": String(length=3),
    "hc_x": Float(),
    "hc_y": Float(),
    "tfs_deprecated": Float(),
    "tfs_zulu_deprecated": Float(),
    "fielder_2": Integer(),
    "umpire": Float(),
    "sv_id": Text(),
    "vx0": Float(),
    "vy0": Float(),
    "vz0": Float(),
    "ax": Float(),
    "ay": Float(),
    "az": Float(),
    "sz_top": Float(),
    "sz_bot": Float(),
    "hit_distance_sc": Float(),
    "launch_speed": Float(),
    "launch_angle": Float(),
    "effective_speed": Float(),
    "release_spin_rate": Float(),
    "release_extension": Float(),
    "game_pk": Integer(),
    "pitcher.1": Integer(),
    "fielder_2.1": Integer(),
    "fielder_3": Integer(),
    "fielder_4": Integer(),
    "fielder_5": Integer(),
    "fielder_6": Integer(),
    "fielder_7": Integer(),
    "fielder_8": Integer(),
    "fielder_9": Integer(),
    "release_pos_y": Float(),
    "estimated_ba_using_speedangle": Float(),
    "estimated_woba_using_speedangle": Float(),
    "woba_value": Float(),
    "woba_denom": Float(),
    "babip_value": Float(),
    "iso_value": Float(),
    "launch_speed_angle": Float(),
    "at_bat_number": Integer(),
    "pitch_number": Integer(),
    "pitch_name": Text(),
    "home_score": Integer(),
    "away_score": Integer(),
    "bat_score": Integer(),
    "fld_score": Integer(),
    "post_away_score": Integer(),
    "post_home_score": Integer(),
    "post_bat_score": Integer(),
    "post_fld_score": Integer(),
    "if_fielding_alignment": Text(),
    "of_fielding_alignment": Text(),
    "spin_axis": Float(),
    "delta_home_win_exp": Float(),
    "delta_run_exp": Float(),
    "bat_speed": Float(),
    "swing_length": Float(),
    "estimated_slg_using_speedangle": Float(),
    "delta_pitcher_run_exp": Float(),
    "hyper_speed": Float(),
    "home_score_diff": Integer(),
    "bat_score_diff": Integer(),
    "home_win_exp": Float(),
    "bat_win_exp": Float(),
    "age_pit_legacy": Integer(),
    "age_bat_legacy": Integer(),
    "age_pit": Integer(),
    "age_bat": Integer(),
    "n_thruorder_pitcher": Integer(),
    "n_priorpa_thisgame_player_at_bat": Integer(),
    "pitcher_days_since_prev_game": Float(),
    "batter_days_since_prev_game": Float(),
    "pitcher_days_until_next_game": Integer(),
    "batter_days_until_next_game": Integer(),
    "api_break_z_with_gravity": Float(),
    "api_break_x_arm": Float(),
    "api_break_x_batter_in": Float(),
    "arm_angle": Float(),
    "attack_angle": Float(),
    "attack_direction": Float(),
    "swing_path_tilt": Float(),
    "intercept_ball_minus_batter_pos_x_inches": Float(),
    "intercept_ball_minus_batter_pos_y_inches": Float(),
    "spray_angle": Float(),
    "horizontal_launch_speed": Float(),
    "o_swing": Integer(),
    "z_swing": Integer(),
    "o_take": Integer(),
    "z_take": Integer(),
    "swing": Integer(),
    "contact": Integer(),
}

read_dtypes = sqlalchemy_to_pandas_dtypes(dtypes)
